export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const FETCH_CAFES_SUCCESS = 'FETCH_CAFES_SUCCESS';
export const LOGIN_USER_START = 'LOGIN_USER_START';
export const REGISTER_USER_START = 'REGISTER_USER_START';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';


export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';
export const CLEAR_CART = 'CLEAR_CART';
export const COUNT_TOTAL_PRODUCT_CART = 'COUNT_TOTAL_PRODUCT_CART';
export const COUNT_TOTAL_PRICE_CART = 'COUNT_TOTAL_PRICE_CART';


