export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const FETCH_CAFES_SUCCESS = 'FETCH_CAFES_SUCCESS';
export const LOGIN_USER_START = 'LOGIN_USER_START';
export const REGISTER_USER_START = 'REGISTER_USER_START';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';

export const LOAD_USER_DATA_START = 'LOAD_USER_DATA_START';
export const LOAD_USER_DATA_SUCCESS = 'LOAD_USER_DATA_SUCCESS';
export const LOAD_USER_DATA_FAIL = 'LOAD_USER_DATA_FAIL';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';
export const CLEAR_CART = 'CLEAR_CART';
export const COUNT_TOTAL_PRODUCT_CART = 'COUNT_TOTAL_PRODUCT_CART';
export const COUNT_TOTAL_PRICE_CART = 'COUNT_TOTAL_PRICE_CART';

export const FILL_CREDIT_CARD_START = 'FILL_CREDIT_CARD_START';
export const FILL_CREDIT_CARD_SUCCESS = 'FILL_CREDIT_CARD_SUCCESS';
export const REGISTER_CREDIT_CARD_START = 'REGISTER_CREDIT_CARD_START';
export const REGISTER_CREDIT_CARD_SUCCESS = 'REGISTER_CREDIT_CARD_SUCCESS';
export const UPDATE_USER_CREDITS_SUCCESS = 'UPDATE_USER_CREDITS_SUCCESS';

export const CASHIER_CONFIRM_ORDER_START = 'CASHIER_CONFIRM_ORDER_START';
export const CASHIER_CONFIRM_ORDER_SUCCESS = 'CASHIER_CONFIRM_ORDER_SUCCESS';

export const ADD_DETAILS_SCREEN_ITEM = 'ADD_DETAILS_SCREEN_ITEM';


